import { OWNER_HELP_SECTIONS } from './ownerSections.js';
import { buildSitterHelpSections, PUBLIC_SITTER_HELP_OPTIONS } from './sitterSections.js';

/**
 * Catalog published on the marketing Help page (generic names, typical apps shown).
 */
export function buildPublicHelpCatalog() {
  return {
    owner: OWNER_HELP_SECTIONS,
    sitter: buildSitterHelpSections(PUBLIC_SITTER_HELP_OPTIONS)
  };
}

/**
 * @param {{ owner: unknown, sitter: unknown }} catalog
 */
export function serializePublicHelpCatalog(catalog) {
  return `/** Generated by scripts/build-website-help.mjs — do not edit by hand. */\nexport const PUBLIC_HELP_CATALOG = ${JSON.stringify(catalog, null, 2)};\n`;
}
